### ISSUE TITLE
開発環境セットアップ

### ISSUE THREAD

**Issue by y4shiro** [y4shiro/sunset-time-notify-achived#1]
セットアップに必要な項目リスト化したので進めていく。  

## Todo
- [x] Next.js インストール
- [x] リポジトリ作成
- [x] 不要なファイル削除
- [x] src ディレクトリ追加
- [x] TS 導入
- [x] ESLint 導入
- [x] Prettier 導入
- [x] Chakra UI 導入
- [x] Jest 導入
- [x] Renovate 導入
- [ ] Storybook 導入
- [x] Lighthouse CI 導入
- [x] Vercel あたりと連携

**Comment by y4shiro** [comment]
Storybook は今回見送ることにしました。
